using System;
using System.Threading.Tasks;
using GottaManagePlus.Services;
using GottaManagePlus.ViewModels;

namespace GottaManagePlus.Utils;

/// <summary>
/// A static class with utilities for <see cref="DialogService"/> class.
/// </summary>
public static class DialogServiceUtils
{
    /// <summary>
    /// The type of answers a prompted user can respond.
    /// </summary>
    public enum QuestionAnswerType
    {
        YesOrNo = 0,
        AllowOrDisallow,
        ProceedOrCancel
    }
    
    /// <summary>
    /// Initiates an asynchronous loading process for the specified dialog view model. 
    /// Upon completion, it displays either a failure or success confirmation dialog based on the outcome of the initial operation.
    /// </summary>
    /// <param name="dialogService">The service instance responsible for managing dialog interactions.</param>
    /// <param name="failDialogDescription">A descriptive message to be presented if the loading operation fails.</param>
    /// <param name="successDialogDescription">A descriptive message to be presented if the loading operation succeeds.</param>
    /// <param name="args">The arguments for the <see cref="LoadingDialogViewModel"/> setup.</param>
    /// <returns><see langword="true"/> if the loading process was a success operation; otherwise, <see langword="false"/>.</returns>
    /// <remarks>
    /// Set up the dialog with the following parameters:
    /// <list type="number">
    ///     <item><description><see cref="string"/> Title (optional)</description></item>
    ///     <item><description><see cref="string"/> Status (optional)</description></item>
    ///     <item><description><see cref="Delegate"/> loadingFunc</description></item>
    ///     <item><description><see cref="object"/>[] args (Optional)</description></item>
    /// </list>
    /// </remarks>
    public static async Task<bool> GenerateLoadingProcess(
        this DialogService dialogService,
        string? failDialogDescription,
        string? successDialogDescription,
        params object?[] args)
    {
        // Attempt to do task generated by the dialog.
        var loadingDialog = dialogService.GetDialog<LoadingDialogViewModel>();
        loadingDialog.Prepare(args);
        if (!await dialogService.ShowDialog(loadingDialog))
        {
            // If failure, show fail dialog.
            if (!string.IsNullOrEmpty(failDialogDescription))
                await dialogService.NotifyUser(Constants.FailDialog, failDialogDescription);
            
            return false;
        }

        // If success, show success dialog.
        if (!string.IsNullOrEmpty(successDialogDescription))
            await dialogService.NotifyUser(Constants.SuccessDialog, successDialogDescription);

        return true;
    }

    /// <summary>
    /// Prompts the user with a specific question and title, awaiting their confirmation via a modal dialog.
    /// </summary>
    /// <param name="dialogService">The service instance responsible for managing dialog interactions.</param>
    /// <param name="title">The title displayed at the top of the confirmation dialog.</param>
    /// <param name="question">The primary question text presented to the user.</param>
    /// <param name="answerType">The answers available for the user.</param>
    /// <returns>
    /// <see langword="true"/> if the user confirms the action (selects "Yes"); otherwise, <see langword="false"/>.
    /// </returns>
    public static async Task<bool> PromptUserQuestion(this DialogService dialogService, string title, string question, QuestionAnswerType answerType = QuestionAnswerType.YesOrNo)
    {
        // Get the dialog.
        var confirmViewModel = dialogService.GetDialog<ConfirmDialogViewModel>();

        // Prepare and display.
        var answer = answerType.AnswerToString();
        confirmViewModel.Prepare(null, title, question, answer.Yes, answer.No);
        await dialogService.ShowDialog(confirmViewModel);

        // Return confirmation.
        return confirmViewModel.Confirmed;
    }
    
    /// <summary>
    /// Raises a dialog telling the user something.
    /// </summary>
    /// <param name="dialogService">The service instance responsible for managing dialog interactions.</param>
    /// <param name="title">The title displayed at the top of the confirmation dialog.</param>
    /// <param name="message">The message displayed at the middle of the confirmation dialog.</param>
    /// <param name="confirmationButton">The label for the confirmation button.</param>
    public static async Task NotifyUser(this DialogService dialogService, string title, string message, string? confirmationButton = null)
    {
        var messageDialog = dialogService.GetDialog<ConfirmDialogViewModel>();
        messageDialog.Prepare(true, title, message, confirmationButton);
        await dialogService.ShowDialog(messageDialog);
    }
    
    // ---- Private API -----
    /// <summary>
    /// Converts a <see cref="QuestionAnswerType"/> to its <see langword="string"/> form.
    /// </summary>
    /// <param name="answerType">The answer type for conversion.</param>
    /// <returns>A <see cref="Tuple{string, string}"/> for a <c>Yes</c> and a <c>No</c>.</returns>
    private static (string Yes, string No) AnswerToString(this QuestionAnswerType answerType) => answerType switch
    {
        QuestionAnswerType.YesOrNo => ("Yes", "No"),
        QuestionAnswerType.AllowOrDisallow => ("Allow", "Disallow"),
        QuestionAnswerType.ProceedOrCancel => ("Proceed", "Cancel"),
        _ => ("Yes", "No")
    };
}