using GottaManagePlus.Models.UI;
using GottaManagePlus.Services;
using GottaManagePlus.ViewModels;

namespace GottaManagePlus.Utils;

/// <summary>
/// A static class with utilities for <see cref="DialogService"/> class.
/// </summary>
public static class DialogServiceUtils
{
    /// <summary>
    /// The type of answers a prompted user can respond.
    /// </summary>
    public enum QuestionAnswerType
    {
        YesOrNo = 0,
        AllowOrDisallow,
        ProceedOrCancel,
        AdaptOrIgnore
    }

    /// <param name="dialogService">The service instance responsible for managing dialog interactions.</param>
    extension(DialogService dialogService)
    {
        /// <summary>
        /// Executes multiple loading tasks concurrently and displays a multi-loading dialog.
        /// Returns a tuple indicating overall success and the collected results from each task.
        /// </summary>
        /// <param name="failDialogDescription">Message shown if any task fails.</param>
        /// <param name="successDialogDescription">Message shown if all tasks succeed.</param>
        /// <param name="title">Title of the loading dialog.</param>
        /// <param name="status">Status text displayed during loading.</param>
        /// <param name="loadingViewModels">The view models for each loading task.</param>
        /// <returns>A tuple where <c>Success</c> is <see langword="true"/> if all tasks completed successfully, otherwise <see langword="false"/>, and <c>Result</c> contains the list of results from each task.</returns>
        public async Task<(bool Success, List<object?> Result)> GenerateGenericMultiLoadingProcess(string? failDialogDescription,
            string? successDialogDescription, string? title, string? status, params LoadingDialogViewModel[] loadingViewModels)
        {
            // Attempt to do task generated by the dialog.
            var loadingDialog = dialogService.GetDialog<MultiLoadingDialogViewModel>();
            loadingDialog.Prepare(title, status);
            
            // Add the loading view models to the dialog
            foreach (var vm in loadingViewModels)
                loadingDialog.InsertLoadingTask(vm);
            
            if (!await dialogService.ShowDialog(loadingDialog))
            {
                // If failure, show fail dialog.
                if (!string.IsNullOrEmpty(failDialogDescription))
                    await dialogService.NotifyUser(Constants.FailDialog, failDialogDescription);
                return (false, loadingDialog.Results);
            }

            // If success, show success dialog.
            if (!string.IsNullOrEmpty(successDialogDescription))
                await dialogService.NotifyUser(Constants.SuccessDialog, successDialogDescription);
            
            return (true, loadingDialog.Results);
        }

        /// <summary>
        /// Executes multiple loading tasks and returns a list of boolean results indicating the success of each task.
        /// </summary>
        /// <param name="failDialogDescription">Message shown if any task fails.</param>
        /// <param name="successDialogDescription">Message shown if all tasks succeed.</param>
        /// <param name="title">Title of the loading dialog.</param>
        /// <param name="status">Status text displayed during loading.</param>
        /// <param name="loadingViewModels">The view models for each loading task.</param>
        /// <returns>A list of nullable booleans where each value corresponds to the result of its respective task; <see langword="true"/> for success, <see langword="false"/> for failure, or <see langword="null"/> if no result was produced.</returns>
        public async Task<List<bool?>> GenerateBooleanMultiLoadingProcess(string? failDialogDescription,
            string? successDialogDescription, string? title, string? status, params LoadingDialogViewModel[] loadingViewModels) =>
            (await dialogService.GenerateGenericMultiLoadingProcess(failDialogDescription, successDialogDescription, 
                title, status, loadingViewModels))
            .Result.ConvertAll(o => (bool?)o);
        
        /// <summary>
        /// Initiates an asynchronous loading process for the specified dialog view model. 
        /// Upon completion, it displays either a failure or success confirmation dialog based on the outcome of the initial operation.
        /// </summary>
        /// <param name="failDialogDescription">A descriptive message to be presented if the loading operation fails.</param>
        /// <param name="successDialogDescription">A descriptive message to be presented if the loading operation succeeds.</param>
        /// <param name="args">The arguments for the <see cref="LoadingDialogViewModel"/> setup.</param>
        /// <returns>
        /// A <see cref="Tuple{bool, object}"/> with the following conditions:
        /// <list type="bullet">
        ///     <item><see langword="true"/> if the loading process was a success operation; otherwise, <see langword="false"/>.</item>
        ///     <item>An object with the return value.</item>
        /// </list>
        /// </returns>
        /// <remarks>
        /// Set up the dialog with the following parameters:
        /// <list type="number">
        ///     <item><description><see cref="string"/> Title (optional)</description></item>
        ///     <item><description><see cref="string"/> Status (optional)</description></item>
        ///     <item><description><see cref="Delegate"/> loadingFunc</description></item>
        ///     <item><description><see cref="object"/>[] args (Optional)</description></item>
        /// </list>
        /// </remarks>
        public async Task<(bool Success, object? Result)> GenerateGenericLoadingProcess(string? failDialogDescription,
            string? successDialogDescription,
            params object?[]? args)
        {
            // Attempt to do task generated by the dialog.
            var loadingDialog = dialogService.GetDialog<LoadingDialogViewModel>();
            loadingDialog.Prepare(args);
            
            // Do the start task here.
            if (!await StartTaskWaiter())
            {
                // If failure, show fail dialog.
                if (!string.IsNullOrEmpty(failDialogDescription))
                    await dialogService.NotifyUser(Constants.FailDialog, failDialogDescription);
                return (false, loadingDialog.Result);
            }

            // If success, show success dialog.
            if (!string.IsNullOrEmpty(successDialogDescription))
                await dialogService.NotifyUser(Constants.SuccessDialog, successDialogDescription);
            
            return (true, loadingDialog.Result);

            // Make an anonymous function for returning the started task.
            async Task<bool> StartTaskWaiter() => await dialogService.ShowDialog(loadingDialog, dialog => dialog.StartTask());
        }
        /// <summary>
        /// Initiates an asynchronous loading process for the specified dialog view model. 
        /// Upon completion, it displays either a failure or success confirmation dialog based on the outcome of the initial operation.
        /// </summary>
        /// <param name="failDialogDescription">A descriptive message to be presented if the loading operation fails.</param>
        /// <param name="successDialogDescription">A descriptive message to be presented if the loading operation succeeds.</param>
        /// <param name="args">The arguments for the <see cref="LoadingDialogViewModel"/> setup.</param>
        /// <returns><see langword="true"/> if the loading process was a success operation; otherwise, <see langword="false"/>.</returns>
        /// <remarks>
        /// Set up the dialog with the following parameters:
        /// <list type="number">
        ///     <item><description><see cref="string"/> Title (optional)</description></item>
        ///     <item><description><see cref="string"/> Status (optional)</description></item>
        ///     <item><description><see cref="Delegate"/> loadingFunc</description></item>
        ///     <item><description><see cref="object"/>[] args (Optional)</description></item>
        /// </list>
        /// </remarks>
        public async Task<bool> GenerateBooleanLoadingProcess(string? failDialogDescription,
            string? successDialogDescription,
            params object?[]? args) =>
            (await dialogService.GenerateGenericLoadingProcess(failDialogDescription, successDialogDescription, args))
            .Success;

        /// <summary>
        /// Prompts the user with a specific question and title, awaiting their confirmation via a modal dialog.
        /// </summary>
        /// <param name="title">The title displayed at the top of the confirmation dialog.</param>
        /// <param name="question">The primary question text presented to the user.</param>
        /// <param name="answerType">The answers available for the user.</param>
        /// <param name="container">The container for log display.</param>
        /// <returns>
        /// <see langword="true"/> if the user confirms the action (selects "Yes"); otherwise, <see langword="false"/>.
        /// </returns>
        public async Task<bool> PromptUserQuestion(string title, string question, QuestionAnswerType answerType = QuestionAnswerType.YesOrNo, LogContainer? container = null)
        {
            // Get the dialog.
            var confirmViewModel = dialogService.GetDialog<ConfirmDialogViewModel>();

            // Prepare and display.
            var answer = answerType.AnswerToString();
            confirmViewModel.Prepare(null, title, question, answer.Yes, answer.No, null, container);
            await dialogService.ShowDialog(confirmViewModel);

            // Return confirmation.
            return confirmViewModel.Confirmed;
        }

        /// <summary>
        /// Raises a dialog telling the user something.
        /// </summary>
        /// <param name="title">The title displayed at the top of the confirmation dialog.</param>
        /// <param name="message">The message displayed at the middle of the confirmation dialog.</param>
        /// <param name="confirmationButton">The label for the confirmation button.</param>
        /// <param name="container">The container for displaying logs.</param>
        public async Task NotifyUser(string title, string message, string? confirmationButton = null, LogContainer? container = null)
        {
            var messageDialog = dialogService.GetDialog<ConfirmDialogViewModel>();
            messageDialog.Prepare(true, title, message, confirmationButton, null, null, container);
            await dialogService.ShowDialog(messageDialog);
        }
    }

    // ---- Private -----
    /// <summary>
    /// Converts a <see cref="QuestionAnswerType"/> to its <see langword="string"/> form.
    /// </summary>
    /// <param name="answerType">The answer type for conversion.</param>
    /// <returns>A <see cref="Tuple{string, string}"/> for a <c>Yes</c> and a <c>No</c>.</returns>
    private static (string Yes, string No) AnswerToString(this QuestionAnswerType answerType) => answerType switch
    {
        QuestionAnswerType.YesOrNo => ("Yes", "No"), // TODO: Here needs localization
        QuestionAnswerType.AllowOrDisallow => ("Allow", "Disallow"),
        QuestionAnswerType.ProceedOrCancel => ("Proceed", "Cancel"),
        QuestionAnswerType.AdaptOrIgnore => ("Adapt", "Ignore"),
        _ => ("Yes", "No")
    };
}