using System;
using System.Collections.Generic;
using GottaManagePlus.Models.UI;
using Tomlyn.Serialization;

namespace GottaManagePlus.Models;

/// <summary>
/// An object that represents the basic data inside a compressed profile.
/// </summary>
public class ProfileMetadata
{
    // Constant value for version support
    [TomlIgnore]
    public const int CurrentVersion = 1;
    
    // Default instance
    public static ProfileMetadata Default => new ProfileMetadata
    {
        EstimatedBytesLength = 100,
        Description = "This is a default profile generated by the application! You can rename this description if you wish.",
        CreationDate = DateTime.Now,
        LastUpdateDate = DateTime.Now
    };
    
    // [Basic Info]
    [TomlRequired] public string Name { get; set; } = "Profile";
    [TomlRequired] public int Version { get; set; } = CurrentVersion;
    public long EstimatedBytesLength { get; set; }
    public string? Description { get; set; }
    [TomlRequired] public DateTime CreationDate { get; set; }
    [TomlRequired] public DateTime LastUpdateDate { get; set; }
    
    // [Profile Content]
    public List<string>? ConfigurationFiles { get; set; }
    public List<string>? PatcherFiles { get; set; }
    public List<string>? ModDataFiles { get; set; }
    
    // [Internal Metadata]
    [TomlIgnore] public string? ProfilePath;
}