using System;
using System.Collections.Generic;
using Tomlyn.Serialization;

namespace GottaManagePlus.Models;

/// <summary>
/// An object that represents the basic data inside a compressed profile.
/// </summary>
public class ProfileMetadata
{
    // Constant value for version support
    [TomlIgnore]
    public const int CurrentVersion = 1;
    
    // Default instance
    public static ProfileMetadata Default => new()
    {
        EstimatedBytesLength = 100,
        Description = "This is a default profile generated by the application! You can rename this description if you wish.",
        CreationDate = DateTime.Now,
        LastUpdateDate = DateTime.Now
    };
    
    // [Basic Info]
    [TomlRequired] public string Name { get; set; } = "Profile";
    [TomlRequired] public int Version { get; set; } = CurrentVersion;
    public long EstimatedBytesLength { get; set; }
    public string? Description { get; set; }
    [TomlRequired] public DateTime CreationDate { get; set; }
    [TomlRequired] public DateTime LastUpdateDate { get; set; }
    
    // [Profile Content]
    /*
     * What should the profile expect from this data?
     * CONFIGS & PATCHERS: the profile should expect the direct path to them (the destination path).
     * In this case, the profile itself should always update and scan for new configuration files and patcher files (handled by ProfileStorage).
     * PLUGINS & ASSETS: These are special.
     * The profile should expect the direct path to the DLL files (plugins).
     * For assets, they should expect the LocalPath and Destination to remain the same (immutable data).
     * However, the destination must always be used to localize the folders.
     */
    public List<string> ConfigurationFiles { get; set; } = [];
    public List<string> PatcherFiles { get; set; } = [];
    public List<ModManifest> ModDataFiles { get; set; } = [];
    
    // Overriden Methods
    public override string ToString() => Name;
}